# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ---------------- #
#   Main Configs   #
# ---------------- #
# the subpath of your site, e.g. /blog
baseurl: ""                                   
# the base hostname & protocol for your site, e.g. http://example.com
url: https://www.zorin.xin                    
date_format: "ordinal"
title: Mars丶小石头
subtitle: "let's face reality，loyalty to an ideal !"
description: "欢迎来到 Mars丶小石头 的个人博客"
keywords: Mars丶小石头, 小石头, zorin, bjddd192, 阳磊
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
# source_code: https://github.com/bjddd192/bjddd192.github.io
# description_footer: Copyright©2018 Mars丶小石头 版权所有 ! 

# ---------------- #
#      Author      #
# ---------------- #
author: Mars丶小石头
organization: Wonhigh
organization_url: http://www.wonhigh.cn/
location: Shen Zhen, China
email: bjddd192@163.com
github_username: bjddd192

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
# 指定一页有几篇文章
paginate: 8
lsi: false
quiet: false
# 指定一个摘要分割符号
excerpt_separator: "\n\n\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: bjddd192/bjddd192.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: bjddd192
#     repo: bjddd192.github.io
#     oauth:
#         client_id: 31e4ad5121eef1e33373
#         client_secret: 21c656d5d21d292ce0c2cc9417eb4bd61ef3921e
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: bjddd192
    repo: blog_comments
    clientID: b01faa7f70da0f6acc30
    clientSecret: 236d15f86f11b1652b756f633b977e3f88391a48
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-92003445-1
